version: "3"
services:
  api:
    build:
      context: ./api
    ports:
      - 8080:8080
      
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  
  grafana:
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/:/etc/grafana/provisioning